version: 2.1
    python: circleci/python@1.5.0
    jobs:
    build-and-test: 
        docker:
        - image: cimg/python:3.10.2
        steps:
        - checkout
        - run:
            name: Run tests
            command: python test.py

    workflows:
    sample:
        jobs:
        - build-and-test
