version: 2.1
jobs:
    build-and-test: 
        docker:
            - image: cimg/python:3.10.2
        steps:
            - run:
                command: python test.py

workflows:
    build-and-test: 
        jobs:
            - build-and-test
