version: 2.1
jobs:
    build-and-test: 
        docker:
            - image: cimg/python:3.10.2
        steps:
            - checkout
            - run: 
                name: Creating Python script
                command: |
                  echo "print('TEST PYTHON')" > test.py
                  chmod 755 test.py
            - run:
                command: python test.py

workflows:
    build-and-test: 
        jobs:
            - build-and-test
